### ISSUE TITLE
Can I catch error in console?

### ISSUE THREAD

**Issue by mcmc4519** [laravel/envoy#123]
Hi!
Thank for your work, it's awesome!

Can you help me?

When I run envoy task, while running I have errors in console. 
Can I catch console errors, and stop running envoy task?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
