### ISSUE TITLE
Using Envoy in a Laravel 5.8 app does not work

### ISSUE THREAD

**Issue by freekmurze** [laravel/envoy#134]
When staring an Envoy task from a Laravel 5.8 app, an exception is thrown.

```
 Dotenv\Dotenv::__construct() must be an instance of Dotenv\Loader, string given,
```

It seems caused by the fact that the compiled Envoy php file contains

```
(new \Dotenv\Dotenv(__DIR__, '.env'))->load();
```

It should be:

```
\Dotenv\Dotenv::create(__DIR__, '.env')->load();
```

**Comment by driesvints** [comment]
`Dotenv` doesn't seems to be present in Envoy. Are you sure it's not thrown from somewhere else? Can you post a stacktrace?

**Comment by freekmurze** [comment]
Seems like this my own fault. The `Dotdev` line was defined in my own script. 

Thanks for the help @driesvints
