### ISSUE TITLE
Semicolon in string fails to correctly parse

### ISSUE THREAD

**Issue by jcandan** [laravel/envoy#135]
### Problem/Motivation

I want to color the output from Envoy commands using Bash color codes. These codes contain semicolons. 

The following failed to correctly parse the variable string containing a semicolon.

```
@setup
    $error_msg = "\033[0;31mWarning: Some message.\033[0m\n";
@endsetup

@servers(['local' => 'localhost'])

@task('test', ['on' => 'local'])
    echo {{ $error_msg }}
@endtask
```

The following error occurs:

```
[localhost]: sh: 1: 33mWarning:: not found
[✗] This task did not complete successfully on one of your servers.
```

To prove this is the issue, you can escape the semicolon in the variable string value to get it working:

```
    $error_msg = "\033[0\;31mWarning: Some message.\033[0m\n";
```

### Proposed resolution

Given that the variable string value is wrapped in quotes, it should not be necessary to escape the semicolon within the string.

**Comment by driesvints** [comment]
I can't even get the above example to work. Is this everything in your `Envoy.blade.php` file?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by jcandan** [comment]
I have updated the issue summary.

**Comment by driesvints** [comment]
@jcandan you need to put the content between semicolons before the echo:

```
@setup
    $error_msg = "\033[0;31mWarning: Some message.\033[0m\n";
@endsetup

@servers(['local' => 'localhost'])

@task('test', ['on' => 'local'])
    echo "{{ $error_msg }}"
@endtask
```

Then it'll work.

**Comment by jcandan** [comment]
Oh! I think you mean, "put the content between double-quotes after the echo."

**Comment by driesvints** [comment]
Right :)
