### ISSUE TITLE
Splitting to multiple files

### ISSUE THREAD

**Issue by vpratfr** [laravel/envoy#137]
Not sure if possible at all currently, but the `Envoy.blade.php` file tends to get larger and larger when tasks are added and made more flexible.

I have already externalized most of the configuration and I was wondering if there was a possibility to split the tasks from that file and put them in another file.

If not currently possible, do you think it would technically be easy to add this? I may be able to work on a PR if that is not a huge one.

Thanks!

**Comment by driesvints** [comment]
Please see https://laravel.com/docs/5.8/envoy#setup

It's a PHP file so you can require whatever file you want.

**Comment by vpratfr** [comment]
@driesvints I did not manage to put my task definitions into other file. 

Is the following supposed to work : 

```
// Envoy.blade.php

@include('deployment/tasks.blade.php')

...

@story 
    foo
@endstory
```

```
// deployment/tasks.blade.php

@task('foo', [...])
    ls -al
@endtask 
```

**Comment by driesvints** [comment]
Hmm, it seems this is indeed not possible which I believed otherwise. The include annotation works a bit different from Blade where it also parses the blade include. I believe if we could extend the include partial to also parse other files it might work. It's also a bit confusing that it's called Envoy.blade.php but Blade isn't actual used behind the hood.

**Comment by vpratfr** [comment]
Ok. Thanks for confirming this.

Le ven. 19 avr. 2019 à 12:50, Dries Vints <notifications@github.com> a
écrit :

**Comment by LukaSikic** [comment]
Use `@import` instead of `@include` and it will work as you expected

**Comment by driesvints** [comment]
@LukaSikic that indeed works. I'll try to add it to the docs soon but feel free to send in a PR before me.
