### ISSUE TITLE
add support for sshpass

### ISSUE THREAD

**Issue by yurii-github** [laravel/envoy#139]
We need to have an option for sshpass support

**Comment by driesvints** [comment]
Can you thoroughly explain why this is needed and how it would work?

**Comment by yurii-github** [comment]
the program is `apt-get install sshpass`. it works like regular ssh but with password instead of key
`sshpass -pPASSWORD ssh USER@HOST -pPORT`

According to code currently it works as
```
                $process = new Process(
                    "ssh $target 'bash -se' << \\$delimiter".PHP_EOL
                    .implode(PHP_EOL, $env).PHP_EOL
                    .'set -e'.PHP_EOL
                    .$task->script.PHP_EOL
                    .$delimiter
                );
```

So, it would be nice to have an option make arbitrary command
```
@servers(['web' => ['user@192.168.1.1']])
do like
@servers(['web' => ['sshpass -pPASSWORD ssh user@192.168.1.1 -pPORT']])
```

**Comment by driesvints** [comment]
It seems unwanted to me to add sensitive things like a password to a deploy script.

**Comment by driesvints** [comment]
I'm going to have to close this for now. If there are more questions coming in to support this we might reconsider. Thanks for submitting.

**Comment by yurii-github** [comment]
password will be stored in environment variable. I'm using gitlab

ok
