### ISSUE TITLE
Returns to home directory on every task execution

### ISSUE THREAD

**Issue by m-triassi** [laravel/envoy#140]
- Envoy Version: 1.5.0
- Laravel Version: 5.8.18
- PHP Version: 7.2.8
- Database Driver & Version: Mysql 5.7.23

### Description:
When executing a story directive on some remote server (CentOS 7) , each task in the story first returns to the home directory before executing the contents of the task, eg:

```
@story('staging', ['on' => 'staging'])
    cdSiteStaging
    git
    migrate
    composer
    npmInstallAndDev
    compileComponents
@endstory

@task('cdSiteStaging')
    cd /var/www/website/docroot
@endtask

@task('git')
    @if($branch)
        git pull origin {{ $branch }}
    @else
        git pull origin master
    @endif
@endtask
```

### Steps To Reproduce:
Happens on a CentOS 7 server when executing the above story, eg: `envoy run staging`

**Comment by driesvints** [comment]
This is the default behavior. All of your tasks will start from the default login location for your user. Your story block is just to define a group of tasks. This is because different tasks could be run in different locations. You'll have to cd to the correct location on each task.
