### ISSUE TITLE
Support passing variables into Envoy tasks

### ISSUE THREAD

**Issue by connecteev** [laravel/envoy#142]
I don't think envoy supports a way to pass variables into tasks. In this (simplified) example, is it possible to NOT replicate 'common' for s1 and s2?

```
@story('s1')
    _task_s1
    common
@endstory

@story('s2')
    _task_s2
    common
@endstory

@task('_task_s1')
    file=".env_local"
@endtask

@task('_task_s2')
    file=".env_prod"
@endtask

@task('common')
    echo "file: {{ $file }}";
    #rm -rf {{ $file }}
@endtask

```

The above example doesnt work and results in:
```
$ envoy run s1
[localhost]: file:

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by connecteev** [comment]
@driesvints sounds good, I'll ask on Discord. Assuming there's a way to do this, based on what you're implying.
