### ISSUE TITLE
Suggestion: Allow a subtask to be called from a parent task.

### ISSUE THREAD

**Issue by connecteev** [laravel/envoy#143]
Suggestion: Allow a subtask to be called from a parent task.

```
@story('s1', ['on' => ['localhost']])
    _task_s1
    common
@endstory

@task('_task_s1')
    subtask
@endtask

@task('common')
    echo "common";
@endtask

@task('subtask')
    echo "subtask called";
@endtask
```

This doesnt work and results in:
```
$ envoy run s1
[localhost]: sh: subtask: command not found
[✗] This task did not complete successfully on one of your servers.
```

**Comment by driesvints** [comment]
It's not possible because you can't differentiate between envoy commands and cli commands inside tasks. You'll need to use a different story.

**Comment by connecteev** [comment]
@driesvints without this as a feature, and https://github.com/laravel/envoy/issues/142 either, it results in duplicative code. Just a suggestion for a future release ;)e
