### ISSUE TITLE
Cannot use @if within @finished

### ISSUE THREAD

**Issue by AdrienPoupa** [laravel/envoy#144]
- Envoy Version: 1.5.0
- Laravel Version: 5.8.17
- PHP Version: 7.2.14
- Database Driver & Version: mysql 5.7.25

### Description:

The `@if` Blade directive cannot be used within `@finished`.

### Steps To Reproduce:

Write the following code

```
@finished
    @if($env != 'local')
        @slack($slack, '#myChannel', "Deployment on {$env}: {$release} complete")
    @endif
    echo "Envoy deployment complete.\r\n";
@endfinished
```

results in

`PHP Parse error:  syntax error, unexpected '<' in /var/www/einsteinfiv2/Envoyac3a4661d761f643c317961bc4f87ff8.php on line 269`

Compiled PHP file:

```
<?php $_vars = get_defined_vars(); $__container->finished(function() use ($_vars) { extract($_vars); 
    <?php if($env != 'local'): ?>
         if (! isset($task)) $task = null; Laravel\Envoy\Slack::make($slack, '#myChannel', "Deployment on {$env}: {$release} complete")->task($task)->send();
    <?php endif; ?>
    echo "Envoy deployment complete.\r\n";
}); ?>
```

I think one should be able to use Blade directive within the `@finished` section

**Comment by driesvints** [comment]
Please fill out the issue template when posting issues.

**Comment by AdrienPoupa** [comment]
Done @driesvints let me know if I can be of any help

**Comment by driesvints** [comment]
@AdrienPoupa you should be able to write plain PHP there. Because it's a closure, short template tags won't work.

```
@finished
    if ($env != 'local') {
        @slack($slack, '#myChannel', "Deployment on {$env}: {$release} complete")
    }

    echo "Envoy deployment complete.\r\n";
@endfinished
```

**Comment by AdrienPoupa** [comment]
Good call, that works, thanks!

However, is it really necessary to make it a closure rather than a normal function?

**Comment by driesvints** [comment]
@AdrienPoupa I'm not super familiar with the internals of Envoy so I believe there probably is a reason for it yeah.
