### ISSUE TITLE
centos 7: envoy command not found

### ISSUE THREAD

**Issue by roshandelpoor** [laravel/envoy#145]
hi

(envoy command not found)
Does this package support Linux Centos7?

Thanks!

**Comment by AdrienPoupa** [comment]
Add your composer bin directory to your PATH environment variable after installing Envoy globally with Composer

https://akrabat.com/global-installation-of-php-tools-with-composer/ttps://serverfault.com/questions/102932/adding-a-directory-to-path-in-centos

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
