### ISSUE TITLE
Class config does not exist

### ISSUE THREAD

**Issue by Shizzen83** [laravel/envoy#148]
- Envoy Version: 1.5.0
- Laravel Version: 5.8.0
- PHP Version: 7.1.3

### Description:
I'm currently trying to setup a deployment onto remote servers.It works fine but I would like going further by using `Illuminate\Foundation\Application` class to be able to inject some dependencies into `@setup` Envoy directive (e.g. retrieve some config or Eloquent models). But I keep getting this error, whatever I tried.

https://nsa40.casimages.com/img/2019/07/22/190722111809435118.png

### Steps To Reproduce:

Run this script
```php
@servers(['localhost' => '127.0.0.1'])

@include('vendor/autoload.php')

@setup
    define('LARAVEL_START', microtime(true));

    $app = require_once __DIR__.'/bootstrap/app.php';

    dump($app->make('config'));
@endsetup

@task('foo', ['on' => 'localhost'])
    ls
@endtask
```

Here is the file generated by Blade compiler, I don't see anything wrong on it
```php
<?php $app = isset($app) ? $app : null; ?>
<?php $__container->servers(['localhost' => '127.0.0.1']); ?>

 <?php require_once('vendor/autoload.php'); ?>

<?php
    define('LARAVEL_START', microtime(true));

    $app = require_once __DIR__.'/bootstrap/app.php';

    dump($app->make('config'));

?>

<?php $__container->startTask('foo', ['on' => 'localhost']); ?>
    ls
<?php $__container->endTask(); ?>
```

Any help would be greatly appreciated, thanks!

**Comment by driesvints** [comment]
I'm afraid this goes a little bit too far as to what Envoy is intended for (running CLI scripts). Sorry.
