### ISSUE TITLE
Feature Request: Manageable Envoy code: Add ability for a story to call another story, or to pass variables into tasks

### ISSUE THREAD

**Issue by connecteev** [laravel/envoy#149]
From all the testing I've done with Envoy over the past few months, there doesn't seem to be an efficient way to make the code DRY (as in, avoid duplication). This is more concerning than it appears because envoy scripts can get very long and complicated, even for basic deployment tasks.

Here are some **real** use-cases I am struggling with at the moment:
Luckily, envoy [accepts passing variables into it from the command line](https://stackoverflow.com/questions/49137848/how-to-pass-arguments-or-params-to-laravel-envoy-task), like so:
```
envoy run build --env=local
envoy run build --env=staging
envoy run build --env=production
envoy run deploy --env=staging
envoy run deploy --env=production
```
The first 3 build for different environments, the last 2 build **and** deploy to the appropriate environment.

All of these use-cases involve 90% of the same set of steps (checkout repo, pick the **right** env file, create build, optionally deploy to the **appropriate** server or keep it local), except they need to do **slightly** different things (like use .env.local instead of .env.production) based on the variables that are passed in. 

Variables passed in from the command line can be 'read' within the @ setup directive, but the problem arises in taking it a step further from there:

1. I don't see a way for a story to call another story dynamically, based on a parameter passed in from the command line.
2. There's also no way that I know of to pass variables into Envoy @ tasks . I had asked for this a few months ago but it [got closed ](https://github.com/laravel/envoy/issues/142). Also, asking on discord, laracasts etc did not get any answers...but I have a hard time believing that I am the only person that has this issue or use case.

I am raising this again because copy-pasting and duplicating 200 lines of a task in envoy.blade.php another 3-4 times makes zero sense to me.

The ask is simple...to provide a way to do # 1 or # 2 above, so that envoy scripts can become a lot more manageable.

**Comment by driesvints** [comment]
I don't think this is possible but feel free to prove me wrong and provide a solution through a PR.

**Comment by connecteev** [comment]
@driesvints based on my very limited knowledge of the envoy source code, it may not be easy to call a story within another one (or even a task within another one).
But isn't passing variables into Envoy @ tasks a possibility and also something that makes sense?

**Comment by connecteev** [comment]
Looked into it again, seems a bit more complex than my current skill level..

**Comment by driesvints** [comment]
> I believe everything is possible

I'm sorry but I really don't think it is. You're working with CLI commands here, not PHP code. The blade control structures only allow you to organise the scripts. Maybe we can find a way to re-use parts. 

I don't have the time to look into this at the moment so feel free to send in a PR if you have time.

**Comment by connecteev** [comment]
@driesvints I guess I'll have to stick with code duplication for now..not ideal but also not the end of the world.

**Comment by driesvints** [comment]
@connecteev I've tried to deep-dive into this but atm I really don't see a use case for this. If you could give me more info and **especially some very concrete examples** on what it is that you're trying to do then I'd be happy to look into this further. 

Feel free to reply.

**Comment by connecteev** [comment]
@driesvints the use-case is basically keeping the code DRY so that I am not replicating a ton of the same code across stories and tasks in my Envoy script. Right now, I have no choice but to do that.

**Comment by connecteev** [comment]
That's what I mean by 'making it more manageable' or modular. More details in the description and https://github.com/laravel/envoy/issues/142. Let me know if anything is unclear about the use-case.

**Comment by driesvints** [comment]
```
@story('s1')
    _task_s1
    common
@endstory

@story('s2')
    _task_s2
    common
@endstory

@task('_task_s1')
    file=".env_local"
@endtask

@task('_task_s2')
    file=".env_prod"
@endtask

@task('common')
    echo "file: {{ $file }}";
    #rm -rf {{ $file }}
@endtask
```

I don't understand here why you can't do this with the current functionality:

```
@task('common')
    echo "file: {{ $file }}";
    #rm -rf {{ $file }}
@endtask
```

```
envoy run common --file=".env_local"
```

Like I said: I'll need a very concrete example in order to know what it is that you're trying to achieve.

**Comment by vpratfr** [comment]
Hi,

When dealing with complex deployment, one may want to group tasks into logical units and keep those units consistent. One may not want to create huge tasks and keep tasks as small as possible.

```
{{-- prepare release in local directory --}}
@story('build')
   git-pull
   composer
   npm
@endstory

{{-- send release to server --}}
@story('publish')
   rsync
   artisan-down
   update-symlinks
   artisan-migrate
   artisan-up
@endstory

{{-- reset server for demo --}}
@story('demo-reset')
   artisan-seed
   // more tasks
@endstory

{{-- Next two stories would be nice to be able to build --}}
@story('deploy')
   build
   publish
@endstory

@story('deploy-fresh')
   build
   publish
   demo-reset
@endstory
```

Added value here is that if I change one of the first three stories, the two last ones do not need to be maintained separatly.

If including story from story is somehow difficult, maybe a new concept `macro` may be introduced and would add one layer of grouping to at least allow reusing groups of tasks.

```
{{-- prepare release in local directory --}}
@macro('build')
   git-pull
   composer
   npm
@endmacro

{{-- send release to server --}}
@macro('publish')
   rsync
   artisan-down
   update-symlinks
   artisan-migrate
   artisan-up
@endmacro

{{-- reset server for demo --}}
@macro('demo-reset')
   artisan-seed
   // more tasks
@endmacro

{{-- Next two stories would be nice to be able to build --}}
@story('deploy')
   build
   publish
@endstory

@story('deploy-fresh')
   build
   publish
   demo-reset
@endstory
``` 

Another way to satisfy the same requirement would be to allow calling tasks from other tasks, but I guess that is even less possible, tasks being terminal commands.

**Comment by vpratfr** [comment]
PS : our current (ugly) workaround is to raw php include from a story

```

@story('deploy')
   @php include __DIR__ . './macros/_build.txt'; @endphp
   @php include __DIR__ . './macros/_publish.txt'; @endphp
@endstory

@story('deploy-fresh')
   @php include __DIR__ . './macros/_build.txt'; @endphp
   @php include __DIR__ . './macros/_publish.txt'; @endphp
   @php include __DIR__ . './macros/_demo-reset.txt'; @endphp
@endstory
``` 

with for instance `./macros/_build.txt` which lists the tasks it should group : 

```
git-pull
composer
npm
```

**Comment by vpratfr** [comment]
I have submitted a rather elegant way to implement that feature. 

https://github.com/laravel/envoy/pull/287

Let me know if I missed anything. That works well for us.
