### ISSUE TITLE
Envoy is not working with Supervisor

### ISSUE THREAD

**Issue by caiokawasaki** [laravel/envoy#158]
- Envoy Version: 1.5
- Laravel Version: 5.8.*
- PHP Version: 7.2.19-0ubuntu0.18.04.2

Envoy cant access any server  trought Supervisor... I have a job that create a server in DO then use envoy to connect to it and install docker. But Envoy can't connect to the server in production... What shoul I do?

This is my Supervisor configuration: 

```
[program:queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/api.posit.us/artisan queue:work
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/api.posit.us/storage/logs/queue.log
```

**Comment by caiokawasaki** [comment]
After hours I was able to solve my problem by installing the latest version of Supervisor.

Instead of using the command, `apt-get install supervisor`, I installed with pip: `pip install supervisor`

**Comment by driesvints** [comment]
Glad you solved it
