### ISSUE TITLE
PHP 7.1 not supported anymore

### ISSUE THREAD

**Issue by peterpan666** [laravel/envoy#161]
- Envoy Version: Since 1.6.0
- Laravel Version: 5.1
- PHP Version: 7.0
- Database Driver & Version: N/A

### Description:
Since Envoy 1.6.0, PHP 7.0 is not supported anymore due to syntax at least in this file https://github.com/laravel/envoy/blob/v1.6.0/src/SSHConfigFile.php#L106 and it broke my build. I don't know which solution is the best, either put the supported PHP version in the composer file or use older syntax (or something else)?

I'm willing to make a PR with the solution you choose.

I've fixed the Envoy version to 1.5.0 to fix it but I was hopping that composer could handle it by itself if we set the supported PHP version in the composer file.

### Steps To Reproduce:
Install the latest Envoy version and run an SSH command in a PHP 7.0 environment.

**Comment by driesvints** [comment]
Are you sure? This syntax was introduced in PHP 7.1: https://secure.php.net/manual/en/migration71.new-features.php

**Comment by peterpan666** [comment]
Whoops my bad, I was in a PHP 7.0 env. I’ll update the issue

**Comment by driesvints** [comment]
PHP 7.0 is EOL and not supported anymore sorry.

**Comment by peterpan666** [comment]
Yeah that was my guessing but wouldn’t it make sense to add the supported PHP version in the composer.json file?

**Comment by driesvints** [comment]
Yeah that's true. I've been working on v2 on master and hoping to release that somewhere this month.
