### ISSUE TITLE
How to use @after task

### ISSUE THREAD

**Issue by colorgreen** [laravel/envoy#167]
I want to execute code after specyfic task execution (like e.g after task 'push' sent message to discord. I see @after is implemented but I cant figure out how to use it. I trying something like 
```
@task( 'push', [ 'on' => 'production' ] )
    whoami
    @after
        @discord( 'https://discordapp.com/api/webhooks/63.....t', 'My message' )
    @endafter

@endtask
```

**Comment by GertjanRoke** [comment]
You should place it outside the @task section and you can do a check on the $task variable

like so:
```blade
@after
if ($task === 'push') {
    @discord( 'https://discordapp.com/api/webhooks/63.....t', 'My message' )
}
@endafter
```

For the next time maybe ask this question on forums like https://laracasts.com/discuss or https://laravel.io/

**Comment by colorgreen** [comment]
In `@after` section `$task` is available, but in `@setup` no. It would be nice to have it also here
