### ISSUE TITLE
Envoy doesn't work with windows OS

### ISSUE THREAD

**Issue by iamsajidjaved** [laravel/envoy#170]
Look at the bug in the laravel documentation. It says, 

> Currently, Envoy only supports the Mac and Linux operating systems

This means, Laravel Envoy doesn't work with the Windows operating system and **but my team is using it with windows. I tried also. It works on windows**

https://laravel.com/docs/master/envoy
![image](https://user-images.githubusercontent.com/32770676/68533224-5f9e6980-0347-11ea-85e5-b1fb458dd6a1.png)

**Comment by driesvints** [comment]
It means we only support the Mac and Linux OS. If it works for you on Windows then all for the better 👍
