### ISSUE TITLE
After update "Uncaught TypeError: Argument 1 passed to"

### ISSUE THREAD

**Issue by C0kkie** [laravel/envoy#173]
- Envoy Version: 1.6.1

### Description:
After the update today i am getting the following issue 

$ ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /home/php/.composer/vendor/laravel/envoy/src/RemoteProcessor.php on line 62 and defined in /home/php/.composer/vendor/symfony/process/Process.php on line 140

TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /home/php/.composer/vendor/laravel/envoy/src/RemoteProcessor.php on line 62 in /home/php/.composer/vendor/symfony/process/Process.php on line 140

**Comment by Quynh-Nguyen** [comment]
https://github.com/laravel/envoy/pull/174

I resolved it but maybe we need to waiting for Contributors comment my pull request.

**Comment by ServiceTo** [comment]
How does this get pushed into a new release? Right now all my Laravel Envoy CI/CD is broken because of this error.

Thanks for the quick fix @Quynh-Nguyen!

**Comment by Quynh-Nguyen** [comment]
@ServiceTo 
You should waiting for new version release or you can `composer require laravel/envoy:1.6.1`, 1.6.1 is previous version for temporary solution.

**Comment by ServiceTo** [comment]
@Quynh-Nguyen it's affecting too many projects to make that change on all of them unfortunately, I can do that for the one I'm working on at the moment.  What's the timeline on a release, do we need to do anything to suggest or vote for a new release?

**Comment by Quynh-Nguyen** [comment]
@taylorotwell @driesvints 
Can you please consider about release a patch version for this critical bug?

**Comment by driesvints** [comment]
Released v1.6.3 with the fix.

**Comment by connecteev** [comment]
I am still seeing this with laravel/envoy version 2.1
