### ISSUE TITLE
Server configuration parsing error

### ISSUE THREAD

**Issue by kafein-ben** [laravel/envoy#175]
- Envoy Version: 1.6.3
- Laravel Version: 5.8.35
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10.2.29

### Description:
Since version 1.6.3, servers configured with a port number will be parsed incorrectly, resulting in SSH connection errors.
For example, this configuration @servers(['myserver' => 'user@server -p 2222']) will result in a "ssh: Could not resolve hostname  'user@server -p 2222'" error.
Using the same server configuration in 1.6.2 works ([see this thread](https://github.com/laravel/envoy/pull/132))

### Steps To Reproduce:
add a port configuration to the server config
run

**Comment by driesvints** [comment]
Just released v1.6.4 with a fix. Can you try that one?

**Comment by kafein-ben** [comment]
It is working now with v1.6.4.
Thank you 👍 !
