### ISSUE TITLE
Allow for user input

### ISSUE THREAD

**Issue by redalpha01** [laravel/envoy#176]
Let me start off with saying that I'm not sure whether this is a bug, a feature request or an error on my end BUT:

It would be nice that, when the server you are connected to prompts for input, it is shown on the CLI where the Envoy command is run so that the user can answer that prompt.

Context :
I am trying to deploy a project that is in a secure bitbucket repo with https://{username}@bitbucket.org/{repo} and - while locally it ask me for a prompt with Windows Credential Manager - when I try it on my staging server, it tells me that it cannot find the password 
> fatal: could not read Password for 'https://myname@bitbucket.org': No such device or address"

I'm aware that I can also pass the password as an argument when running Envoy, but somehow having the password in fulltext in my CLI doesn't seem so great.

Note: We also want to be able to keep track of the users deploying through their git username so that's one of the reasons why we're not using something like an SSH key.

If I'm doing anything wrong, any input would be appreciated. 

Thanks!

**Comment by driesvints** [comment]
Yeah that could be useful. Feel free to pr something.

**Comment by driesvints** [comment]
Since this isn't something that we'd work on ourselves anytime soon I'm closing this. But we're still open to PRs.

**Comment by connecteev** [comment]
I too, would love to see this feature in envoy

**Comment by immortalsantee** [comment]
Is this feature available now?
