### ISSUE TITLE
"confirm" directory doesn't work with @include('vendor/autoload.php')

### ISSUE THREAD

**Issue by indosean** [laravel/envoy#189]
- Envoy Version: 2.0.1
- Laravel Version: 5.6.31
- PHP Version: 7.2.28
- Database Driver & Version:

### Description:
When I use the `@include('vendor/autoload.php')` include at the top of my Envoy file the `confirm` directive gives an error.

```
Are you sure you want to run the [golive] task? [y/N]: PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Question\ConfirmationQuestion::getAutocompleterCallback() in /home/USER/.config/composer/vendor/symfony/console/Helper/QuestionHelper.php:108
Stack trace:
#0 /home/USER/.config/composer/vendor/symfony/console/Helper/QuestionHelper.php(61): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\ConfirmationQuestion))

#1 /home/USER/.config/composer/vendor/laravel/envoy/src/Console/Command.php(79): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\ConfirmationQuestion))

#2 /home/USER/.config/composer/vendor/laravel/envoy/src/Console/RunCommand.php(124): Laravel\Envoy\Console\RunCommand->confirmTaskWithUser('golive', Object(Symfony\Component\Console\Question\ConfirmationQuestion)) in /home/USER/.config/composer/vendor/symfony/console/Helper/QuestionHelper.php on line 108
```
This could be because Envoy was installed globally like the docs said - `composer global require laravel/envoy`

### Steps To Reproduce:
When I remove the `@include('vendor/autoload.php')` include then the `confirm` directive works as expected.

I have since seen that for my purpose I didn't need to use `@include('vendor/autoload.php')` but said I would report it anyway.

Thank you

**Comment by driesvints** [comment]
Heya, I just tested this and all works as expected:

```php
@servers(['localhost' => '127.0.0.1'])

@include('vendor/autoload.php')

@task('foo', ['on' => 'localhost', 'confirm' => true])
    ls -la
@endtask
```

**Comment by indosean** [comment]
Hi @driesvints 

I'm pretty sure it is because Envoy was installed globally like the docs said - `composer global require laravel/envoy`

**Comment by driesvints** [comment]
I tried with both global and local envoy.

**Comment by indosean** [comment]
ok fair enough - it's strange. Thanks
