### ISSUE TITLE
@story is not respecting the current directory

### ISSUE THREAD

**Issue by mazedlx** [laravel/envoy#193]
- Envoy Version: 2.0.1
- Laravel Version: 7.11.0
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 8.0.18

### Description:

I have an Envoy.blade.php file that makes use of `@story` and `@task` to split different deployment tasks into smaller, reusable tasks.

```blade
@servers(['web' => ['user@webserver.com']])

@story('deploy')
    cd
    down
    git
    composer
    npm
    optimize
    up
@endstory

@task('cd')
    cd /var/www/html/app-dir
@endtask

@task('down')
    php artisan down
@endtask

@task('up')
    php artisan up
@endtask

@task('git')
    git pull
@endtask

@task('composer')
    composer install --no-dev
    composer update --no-dev
@endtask

@task('npm')
    npm install
    npm run prod
@endtask

@task('optimize')
    php artisan optimize
@endtask
```

### Steps To Reproduce:

When I run `enovy run deploy` the deployment fails with ```Could not open input file: artisan
[✗] This task did not complete successfully on one of your servers.```

I've added `pwd` to the `cd` and `down` task 

```blade
@task('cd')
    cd /var/www/html/app-dir
    pwd
@endtask

@task('down')
    pwd
    php artisan down
@endtask
```

to get the current directory the command is run in, and it seems the directory I cd'ed into gets lost somehow:

```bash
$ envoy run deploy     
[user@webserver.com]: /var/www/html/app-dir <-- after 'cd'
[user@webserver.com]: /home/user <-- before 'down'
[user@webserver.com]: Could not open input file: artisan
[✗] This task did not complete successfully on one of your servers.
```

I am not sure whether this behavior is to be expected or if it is a bug. Thanks in advance :-)

**Comment by driesvints** [comment]
Hey @mazedlx this is correct. Consider tasks the same as envoyer deploy steps where you also need to navigate to the correct directory for each step.
