### ISSUE TITLE
Downloadable .phar

### ISSUE THREAD

**Issue by FrontEndCoffee** [laravel/envoy#195]
Currently, a user must install Envoy globally in the container or machine that it is used on. 

I think it would be very useful to have a .phar available. This would simplify a lot CD containers out there.

Any thoughts?

**Comment by FrontEndCoffee** [comment]
Of course I would be willing to send in a PR

**Comment by driesvints** [comment]
Sorry, but we have no plans for this. You can install envoyer by requiring it on a project basis.
