### ISSUE TITLE
Call to undefined method Symfony\Component\Process\Process::fromShellCommandline()

### ISSUE THREAD

**Issue by kjbrum** [laravel/envoy#197]
- Envoy Version: 2.1.0
- Laravel Version: n/a
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7

### Description:

Getting the following error when trying to run Envoy command to pull remote database.
```
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /Users/username/.composer/global/laravel/envoy/vendor/laravel/envoy/src/RemoteProcessor.php:57
Stack trace:
#0 /Users/username/.composer/global/laravel/envoy/vendor/laravel/envoy/src/SSH.php(29): Laravel\Envoy\RemoteProcessor->getProcess('root@67....', Object(Laravel\Envoy\Task))
#1 /Users/username/.composer/global/laravel/envoy/vendor/laravel/envoy/src/Console/RunCommand.php(175): Laravel\Envoy\SSH->run(Object(Laravel\Envoy\Task), Object(Closure))
#2 /Users/username/.composer/global/laravel/envoy/vendor/laravel/envoy/src/Console/RunCommand.php(157): Laravel\Envoy\Console\RunCommand->passToRemoteProcessor(Object(Laravel\Envoy\Task))
#3 /Users/username/.composer/global/laravel/envoy/vendor/laravel/envoy/src/Console/RunCommand.php(128): Laravel\Envoy\Console\RunCommand->runTaskOverSSH(Object(Laravel\Envoy\Task))
#4 /Users/username/.composer/global/laravel/envoy/vendor/laravel/envoy/src/Console/RunC in /Users/username/.composer/global/laravel/envoy/vendor/laravel/envoy/src/RemoteProcessor.php on line 57
```

### Steps To Reproduce:

Running command: `envoy run db:pull --production`

**Comment by driesvints** [comment]
Update all of your dependencies (also symfony ones)

**Comment by kjbrum** [comment]
I'm using Envoy globally so how would I go about updating the dependencies?

**Comment by driesvints** [comment]
`composer global update`

**Comment by kjbrum** [comment]
I've ran that and just get the following output:
```
Changed current directory to /Users/kylebrumm/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by driesvints** [comment]
Your global installation is probably conflicting with other libraries. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
