### ISSUE TITLE
envoy deploys: Problems running envoy run deploy command

### ISSUE THREAD

**Issue by christian-manrique** [laravel/envoy#198]
- Envoy Version: 2.2.0
- Laravel Version: 6.18.3
- PHP Version: 7.4.8
- Database Driver & Version: mysql 15.1 Distrib 10.3.23-MariaDB

### Description: 
HI There, i need some help please. i have deployed the envoy package successfully at my vagrant homestead laravel box and works like a charm, i implemented the Envoy.blade.php with all task and instructions to make deployments and works pretty well and when i hit on the terminal the "envoy run deploy" all the deployment process goes all right, but considering the deployment on the staging account to test the deployment process (production server) the command who runs the deployment doesn't work... on the server i pulled the changes and even running composer global require laravel/envoy and composer global update but not results, firstly i was having this error "-bash: envoy: command not found" so searching  on google i added some tweaks i added the /.composer/vendor/bin directory (wasn't exist but in my vagrant homestead does exist) besides i added the file ~/.composer/vendor/bin/envoy and i bash it on my ~/.bash_profile adding export PATH="$PATH:$HOME/.composer/vendor/bin" and well i am not having the anymore the error mentioned "-bash: envoy: command not found" but now instead when i hit  envoy run deploy the response is nothing!!, please any advise would help me a lot thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
