### ISSUE TITLE
How to run ssh on Envoy

### ISSUE THREAD

**Issue by vuong-bse** [laravel/envoy#199]
- Envoy Version: 2.0
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version:

### Description:
Sorry, I have a problem using "ssh" in an Envoy Task. I tried searching for some solutions to the problem but it didn't work.
I using Amazon EC2.
So, I have code
```
@servers(['stg'=>'-i ~/.ssh/key.pem user@ip_server'])
@task('deploy',['on'=>'stg'])
  ssh -T -vvv virtual-host001
  cd /var/www/source_code && git checkout staging && git pull
@endtask
```
I can login via terminal like this:
```
ssh -i ~/.ssh/key.pem user@ip_server
ssh virtual-host001
```
=> Go to virtual-host001, I setup on ~/.ssh/config

But, When I run envoy: **envoy run deploy**, I receiver Error message when run command ssh -vvv virtual-host001:
**Pseudo-terminal will not be allocated because stdin is not a terminal.**

It's some output when I add -vvv when call ssh:

> -------------------------------------:  OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
-------------------------------------:  debug1: Reading configuration data /home/user/.ssh/config
-------------------------------------:  debug1: /home/user/.ssh/config line 19: Applying options for ocean-cms
-------------------------------------:  debug1: Reading configuration data /etc/ssh/ssh_config
-------------------------------------:  debug1: /etc/ssh/ssh_config line 58: Applying options for *
-------------------------------------:  Pseudo-terminal will not be allocated because stdin is not a terminal.
-------------------------------------:  debug2: resolving "10.1.10.xxx" port 22
-------------------------------------:  debug2: ssh_connect_direct: needpriv 0
-------------------------------------:  debug1: Connecting to 10.1.10.xxx [10.1.10.xxx] port 22.
-------------------------------------:  debug1: Connection established.
-------------------------------------:  debug1: key_load_public: No such file or directory
-------------------------------------:  debug1: identity file /home/user/.ssh/id_rsa type -1
-------------------------------------:  debug1: key_load_public: No such file or directory
-------------------------------------:  debug1: identity file /home/user/.ssh/id_rsa-cert type -1
-------------------------------------:  debug1: Enabling compatibility mode for protocol 2.0
-------------------------------------:  debug1: Local version string SSH-2.0-OpenSSH_7.4
-------------------------------------:  debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
-------------------------------------:  debug1: match: OpenSSH_7.4 pat OpenSSH* compat 0x04000000
-------------------------------------:  debug2: fd 3 setting O_NONBLOCK
-------------------------------------:  debug1: Authenticating to 10.1.10.xxx:22 as 'user'
-------------------------------------:  debug3: hostkeys_foreach: reading file "/home/user/.ssh/known_hosts"
-------------------------------------:  debug3: record_hostkey: found key type ECDSA in file /home/user/.ssh/known_hosts:4
-------------------------------------:  debug3: load_hostkeys: loaded 1 keys from 10.1.10.xxx
-------------------------------------:  debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
-------------------------------------:  debug3: send packet: type 20
-------------------------------------:  debug1: SSH2_MSG_KEXINIT sent
-------------------------------------:  debug3: receive packet: type 20
-------------------------------------:  debug1: SSH2_MSG_KEXINIT received
-------------------------------------:  debug2: local client KEXINIT proposal
..................
..................
-------------------------------------:  debug1: Next authentication method: gssapi-with-mic
-------------------------------------:  debug1: Unspecified GSS failure.  Minor code may provide more information
-------------------------------------:  No Kerberos credentials available (default cache: KEYRING:persistent:1002)
-------------------------------------:  debug1: Unspecified GSS failure.  Minor code may provide more information
-------------------------------------:  No Kerberos credentials available (default cache: KEYRING:persistent:1002)
-------------------------------------:  debug2: we did not send a packet, disable method
-------------------------------------:  debug3: authmethod_lookup publickey
-------------------------------------:  debug3: remaining preferred: keyboard-interactive,password
-------------------------------------:  debug3: authmethod_is_enabled publickey
-------------------------------------:  debug1: Next authentication method: publickey
-------------------------------------:  debug1: Trying private key: /home/user/.ssh/id_rsa
-------------------------------------:  debug3: sign_and_send_pubkey: RSA SHA256:WKGmvji78sSjNEVbppRr0sqgfjOyU3N21U2GQJnteU0
-------------------------------------:  debug3: send packet: type 50
-------------------------------------:  debug2: we sent a publickey packet, wait for reply
-------------------------------------:  debug3: receive packet: type 52
-------------------------------------:  debug1: Authentication succeeded (publickey).
-------------------------------------:  Authenticated to 10.1.10.xxx ([10.1.10.xxx]:22).
-------------------------------------:  debug2: fd 4 setting O_NONBLOCK
-------------------------------------:  debug2: fd 5 setting O_NONBLOCK
-------------------------------------:  debug2: fd 6 setting O_NONBLOCK
-------------------------------------:  debug1: channel 0: new [client-session]
-------------------------------------:  debug3: ssh_session2_open: channel_new: 0
-------------------------------------:  debug2: channel 0: send open
-------------------------------------:  debug3: send packet: type 90
-------------------------------------:  debug1: Requesting no-more-sessions@openssh.com
-------------------------------------:  debug3: send packet: type 80
-------------------------------------:  debug1: Entering interactive session.
-------------------------------------:  debug1: pledge: network
-------------------------------------:  debug3: receive packet: type 80
-------------------------------------:  debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
-------------------------------------:  debug3: receive packet: type 91
-------------------------------------:  debug2: callback start
-------------------------------------:  debug2: fd 3 setting TCP_NODELAY
-------------------------------------:  debug3: ssh_packet_set_tos: set IP_TOS 0x08
-------------------------------------:  debug2: client_session2_setup: id 0
-------------------------------------:  debug1: Sending environment.
-------------------------------------:  debug3: Ignored env XDG_SESSION_ID
-------------------------------------:  debug3: Ignored env SHELL
-------------------------------------:  debug3: Ignored env SSH_CLIENT
-------------------------------------:  debug3: Ignored env ENVOY_HOST
-------------------------------------:  debug3: Ignored env USER
-------------------------------------:  debug3: Ignored env PATH
-------------------------------------:  debug3: Ignored env MAIL
-------------------------------------:  debug3: Ignored env PWD
-------------------------------------:  debug1: Sending env LANG = en_US.UTF-8
-------------------------------------:  debug2: channel 0: request env confirm 0
-------------------------------------:  debug3: send packet: type 98
-------------------------------------:  debug3: Ignored env MODULEPATH
-------------------------------------:  debug3: Ignored env LOADEDMODULES
-------------------------------------:  debug3: Ignored env HOME
-------------------------------------:  debug3: Ignored env SHLVL
-------------------------------------:  debug3: Ignored env LOGNAME
-------------------------------------:  debug3: Ignored env SSH_CONNECTION
-------------------------------------:  debug3: Ignored env MODULESHOME
-------------------------------------:  debug3: Ignored env LESSOPEN
-------------------------------------:  debug3: Ignored env XDG_RUNTIME_DIR
-------------------------------------:  debug3: Ignored env BASH_FUNC_module()
-------------------------------------:  debug3: Ignored env _
-------------------------------------:  debug2: channel 0: request shell confirm 1
-------------------------------------:  debug3: send packet: type 98
-------------------------------------:  debug2: callback done
-------------------------------------:  debug2: channel 0: open confirm rwindow 0 rmax 32768
-------------------------------------:  debug2: channel 0: rcvd adjust 2097152
-------------------------------------:  debug3: receive packet: type 99
-------------------------------------:  debug2: channel_input_status_confirm: type 99 id 0
-------------------------------------:  debug2: shell request accepted on channel 0
-------------------------------------:  debug2: channel 0: read<=0 rfd 4 len 0
-------------------------------------:  debug2: channel 0: read failed
-------------------------------------:  debug2: channel 0: close_read
-------------------------------------:  debug2: channel 0: input open -> drain
-------------------------------------:  debug2: channel 0: ibuf empty
-------------------------------------:  debug2: channel 0: send eof
-------------------------------------:  debug3: send packet: type 96
-------------------------------------:  debug2: channel 0: input drain -> closed
-------------------------------------:  debug3: receive packet: type 98
-------------------------------------:  debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
-------------------------------------:  debug3: receive packet: type 96
-------------------------------------:  debug2: channel 0: rcvd eof
-------------------------------------:  debug2: channel 0: output open -> drain
-------------------------------------:  debug2: channel 0: obuf empty
-------------------------------------:  debug2: channel 0: close_write
-------------------------------------:  debug2: channel 0: output drain -> closed
-------------------------------------:  debug3: receive packet: type 97
-------------------------------------:  debug2: channel 0: rcvd close
-------------------------------------:  debug3: channel 0: will not send data after close
-------------------------------------:  debug2: channel 0: almost dead
-------------------------------------:  debug2: channel 0: gc: notify user
-------------------------------------:  debug2: channel 0: gc: user detached
-------------------------------------:  debug2: channel 0: send close
-------------------------------------:  debug3: send packet: type 97
-------------------------------------:  debug2: channel 0: is dead
-------------------------------------:  debug2: channel 0: garbage collecting
-------------------------------------:  debug1: channel 0: free: client-session, nchannels 1
-------------------------------------:  debug3: channel 0: status: The following connections are open:
-------------------------------------:  #0 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)
-------------------------------------:  debug3: send packet: type 1
-------------------------------------:  debug1: fd 0 clearing O_NONBLOCK
-------------------------------------:  debug1: fd 1 clearing O_NONBLOCK
-------------------------------------:  debug1: fd 2 clearing O_NONBLOCK
-------------------------------------:  Transferred: sent 2520, received 2356 bytes, in 0.4 seconds
-------------------------------------:  Bytes per second: sent 6810.7, received 6367.5
-------------------------------------:  debug1: Exit status 0

**Can help me explain and that solution for it?**

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
