### ISSUE TITLE
Sending a @finished notification via Telegram doesn't work

### ISSUE THREAD

**Issue by barrasme** [laravel/envoy#203]
# Versions
- Envoy Version: v2.3.1
- Laravel Version: 8.0 (Now)
- PHP Version: 7.3.1
- Database Driver & Version: Mysql 5.7.24

### Description:
I'm trying to send a notification to my customer via Telegram.
I added the @finished to the bottom of my `Envoy.blade.php` file as below (details changed)

`@finished
    @telegram("MyBot","1234567890")
@endfinished
`

### Steps To Reproduce:
When running my `prod` envoy script I see the following error

`PHP Parse error:  syntax error, unexpected '}' in /home/vagrant/code/nsl/Envoy7b733335d6e41d155f181fe7fbef07d2.php on line 49

Parse error: syntax error, unexpected '}' in /home/vagrant/code/nsl/Envoy7b733335d6e41d155f181fe7fbef07d2.php on line 49
`

I was running Laravel 7.X but I took the time to upgrade thinking that may help. 
It didn't

Thanks in advance for your help!

**Comment by driesvints** [comment]
Tried `php artisan view:clear`?

**Comment by driesvints** [comment]
Or removing that php file from above?

**Comment by barrasme** [comment]
@driesvints Thanks for the response.

I have now tried view:clear which hasn't helped.

![CleanShot 2020-10-27 at 18 12 54](https://user-images.githubusercontent.com/2089165/97343988-13ae4280-1880-11eb-81e2-d5dab026124f.png)

> Or removing that php file from above?

Sorry, I'm not sure which file?

**Comment by driesvints** [comment]
The generated Envoy file: Envoy7b733335d6e41d155f181fe7fbef07d2

**Comment by barrasme** [comment]
Hi,
I've removed all the generated EnvoyXXXX files and sadly I still have the same issue.

So I tried a couple of tests, I replaced the @telegram with @discord, I didn't bother with a URL.
When I ran this it came up with the expected issue of an invalid URL but it is finding the method.

` Unable to connect to "discord-webhook-url": 6 Could not resolve host: discord-webhook-url`

I've no idea why but it looks like it can't find the method for telegram

Fingers crossed you can replicate or tell me where I've being stupid!

**Comment by driesvints** [comment]
Just FYI: I've been head over heals in upgrading our libraries for PHP 8 but definitely plan to pick this up eventually.

**Comment by barrasme** [comment]
Thanks. Much appreciated   
  
  
  
    
  

  
  
>

**Comment by driesvints** [comment]
I tried this out and can't reproduce it. The Telegram bot successfully received the message:

<img width="713" alt="Screenshot 2020-11-05 at 17 08 39" src="https://user-images.githubusercontent.com/594614/98265640-9ecabf00-1f89-11eb-9b84-7401c708c229.png">

My script:

```blade
@servers(['localhost' => '127.0.0.1'])

@task('foo', ['on' => 'localhost'])
    ls -la
@endtask

@finished
    @telegram('xxxxx:xxxxx', 'xxxxx')
@endfinished
```

Think it's best that you try a support channel for this one.
