### ISSUE TITLE
Declared variables in @setup override passed variables from commandline 

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/envoy#205]
- Envoy Version: 2.4.0
- Laravel Version: 8.15.0
- PHP Version: 7.4.12
- Database Driver & Version:

### Description:
Variables passed by command line aren't considered when the same name is used in @setup

### Steps To Reproduce:
```php
@servers(['localhost' => ['127.0.0.1'], 'something' => '192.168.0.1'])

@setup
    $enabled = true;
@endsetup

@task('run-tests', ['on' => 'localhost'])
    @if ($enabled)
        echo {{ $enabled }}
    @endif
@endtask
```

```bash script
$ envoy run run-tests --enabled=false
[127.0.0.1]: 1
```
Ideal scenario is that we can override that values.
In right now, we have to pass multiple checking values in if statement ;/

**Comment by driesvints** [comment]
You solve this by declaring it with the input from the CLI in the `@setup` directive as documented here: https://laravel.com/docs/8.x/envoy#setup

```blade
@setup
    $enabled = $enabled ?? true;
@endsetup
````
