### ISSUE TITLE
When run command all task command are executed locally - when waiting for password

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/envoy#207]
- Envoy Version: 2.4.0
- Laravel Version: 8.15.0
- PHP Version: 7.4.12
- Database Driver & Version:

### Steps To Reproduce:
```php
@servers(['localhost' => ['127.0.0.1'], 'uat' => '192.168.0.1])

@task('deploy-uat', ['on' => 'uat'])
    cd /data/www/html
    pwd
    ls -lat
@endtask
```
then
```bash
user@nd0:/var/www/html$ envoy run deploy-uat
[127.0.0.1]: /var/www/html
[127.0.0.1]:  sh: 1: cd: can't cd to /data/www/tml
[127.0.0.1]: total 3320
[127.0.0.1]: drwxrwxr-x  16 www-data www-data    4096 lis 18 19:56 .
[127.0.0.1]: -rw-rw-r--   1 user user       1034 lis 18 19:56 Envoy.blade.php
//
[127.0.0.1]: drwxr-xr-x   4 usesr user       4096 lis  4 19:51 ..
remoteuser192.168.0.1's password: 
```
So all commands are executed locally and after that Envoyer ask for password?

**Comment by driesvints** [comment]
Hey @LocalHeroPro. You're posting quite a bit of issues which can easily be asked in a support channel. Please try to use a support channel first as this issue tracker is mainly for reporting bugs (see the issue templates when you open an issue).

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
