### ISSUE TITLE
Hyphenated parameters don't translate to usable variables

### ISSUE THREAD

**Issue by simonhamp** [laravel/envoy#210]
Imagine the following command:

```
envoy run deploy --no-npm
```

In the Envoy script, I then want to be able to do this:

```
@if(! $no_npm)
    npm install
    npm run prod
@endif
```

But it doesn't work, because `$no_npm` never evaluates to `true`. So my guess is this is the wrong variable name. However, I can't find any instructions in the docs that help with this situation.

What should the signature of variable be in the Envoy blade to use the value of the `--no-npm` flag? Ones that I've tried that didn't work:

```
$no_npm
$noNpm
${'no-npm'}
```

Is there a convention in Envoy for converting hyphen-separated argument names to usable PHP variables?

My solutions to this so far are:

1) Change the signature of the command to:

```
envoy run deploy --no_npm
```

There are a few [good](https://stackoverflow.com/questions/1253679/should-command-line-options-in-posix-style-operating-systems-be-underscore-style) [sources](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) suggesting that this isn't ideal:

>Long options consist of ‘--’ followed by a name made of alphanumeric characters and dashes. Option names are typically one to three words long, with hyphens to separate words.

2) So if we keep the hyphen, the only way I've been able to access the value in the script is by this:

```
@if(! ($__data['no-npm'] ?? false))
    npm install
    npm run prod
@endif
```

Which I'm sure you'll agree is pretty ugly.

I'm happy to dig more into this and provide a PR for a fix... just want to make sure I'm not missing something obvious.

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.

**Comment by simonhamp** [comment]
I chose 'Feature Request' as i didn't see this a bug or other kind of issue. GitHub didn't present me with a template when i selected that 🤷‍♂️

**Comment by driesvints** [comment]
Ah, because you said:

> I'm happy to dig more into this and provide a PR for a fix

Which led me to believe you meant this as a bug report.

**Comment by simonhamp** [comment]
I'll choose my words more carefully next time 😉
