### ISSUE TITLE
vendor/bin/envoy run as text not a php file

### ISSUE THREAD

**Issue by hsmfawaz** [laravel/envoy#213]
- Envoy Version: 2.5.0
- Laravel Version: 8.23.1
- PHP Version: 7.4.13
- Database Driver & Version:
- OS : Windows 10 Pro Build:19042.746
### Description:
simple after installing the package via 
`composer require laravel/envoy --dev`
i tried to run the following command
`php vendor/bin/envoy`
and i got the following response

```php
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../laravel/envoy/bin" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi


"${dir}/envoy" "$@"

```

**Comment by driesvints** [comment]
Please see the intro note about Windows support here: 

<img width="730" alt="Screenshot 2021-01-21 at 11 47 30" src="https://user-images.githubusercontent.com/594614/105340664-79d80680-5bde-11eb-86d2-8c051aaa5533.png">

**Comment by hsmfawaz** [comment]
Oh sorry didn't notice that because i always run it under linux 
thanks for your time
