### ISSUE TITLE
SSL Failure when trying to use Telegram

### ISSUE THREAD

**Issue by arsamme** [laravel/envoy#214]
- Envoy Version: 2.5.0
- Laravel Version: 8.18.1
- PHP Version: 8.0.0

### Description:
cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.telegram.org/bot1248907810:AAFVU6ubAVjn5GfCdtc3uIwf8s8WGHPKSL4/sendMessage  

### Steps To Reproduce:
Use @telegram in @finished directive.

**Comment by driesvints** [comment]
This doesn't seems to be an Envoy issue but rather an SSL issue at Telegram or something else.

**Comment by arsamme** [comment]
@driesvints This occurs for discord and slack too. Envoy should have an option for configuring ssl or something.

**Comment by driesvints** [comment]
@arsamme this is the first report we've ever had about this. I doubt this is a widespread issue.
