### ISSUE TITLE
Can series have parallel option like tasks do?

### ISSUE THREAD

**Issue by sublime392** [laravel/envoy#215]
I have a deployment story, and I want it to run sequentially, one server at a time. However, it will actually perform one task for every server before moving on to the next task. i.e. for 
```
@servers(['one' => 'one.com', 'two' => 'two.com'])

@story('deploy', ['on' => ['one', 'two']])
    touch1
    touch2
@endstory

@task('touch1')
    touch one
@endtask

@task('touch2')
    touch two
@endtask
```

will run one>touch1, two>touch1, one>touch2, two>touch2,
 but what I need it to do is one>touch1, one>touch2, two>touch1, two>touch2

**Comment by driesvints** [comment]
That's unfortunately not possible in Envoy atm. Servers are assigned to their respective tasks and those tasks are executed in order based on a story.

Does https://laravel.com/docs/8.x/envoy#parallel-execution work in this case for you?


```
@servers(['one' => 'one.com', 'two' => 'two.com'])

@story('deploy', ['on' => ['one', 'two'], 'parallel' => true])
    touch1
    touch2
@endstory

@task('touch1')
    touch one
@endtask

@task('touch2')
    touch two
@endtask
```

**Comment by sublime392** [comment]
@driesvints the `@story` doesn't currently have the parallel option. That is the enhancement I am looking for - I want to be able to have the `@story` run with `parallel=false` because its current operation is effectively `parallel=true`. I need it to complete the entire set of tasks for the first server before moving on to the next server.

Reason why this behavior would be a useful feature: 
An update can result in incompatible changes between the database structure and models/logic. So there is a sort of timing issue during a deployment between linking in the updated code, running migrations, restarting queue workers, etc. It would be rather messy to do all of this within a single task; multiple tasks make it easier to read/maintain the deployment process. However, you can't exactly link in the updated code, and then wait for that step to happen on twenty other servers before running the migration step.

**Comment by driesvints** [comment]
Right. At the moment stories indeed don't support this sorry. You can however attempt a PR if you would like to see this added. Thanks.

**Comment by sublime392** [comment]
*one wonders if this was left open as an enhancement request instead of being closed, might not some other helpful soul take it on?

**Comment by driesvints** [comment]
We only keep enhancement issues open if we plan on working on those ourselves. Otherwise we appreciate PRs.

**Comment by ErikDohmen** [comment]
@sublime392 would this be an option for you?

`
@story('deploy-all')
   deploy-on-one
   deploy-on-two
@endstory

@story('deploy-on-one',['on' => 'one'])
   deploy
@endstory

@story('deploy-on-two',['on' => 'two'])
   deploy
@endstory

@story('deploy')
    touch1
    touch2
@endstory
`

Then you would be able to call the deploy-all to do a full deployment or have the option to do a single deployment on one of the servers.

Just a thought

**Comment by ErikDohmen** [comment]
@sublime392 would this be an option for you?

```
@story('deploy-all')
   deploy-on-one
   deploy-on-two
@endStory

@story('deploy-on-one',['on' => 'one'])
   deploy
@endStory

@story('deploy-on-two',['on' => 'two'])
   deploy
@endStory

@story('deploy')
   touch1
   touch2
@endStory

```

Then you would be able to call the deploy-all to do a full deployment or have the option to do a single deployment on one of the servers.

Just a thought

**Comment by sublime392** [comment]
@ErikDohmen thanks for taking a look, but it seems that stories can't nest. When I try to call a story from a story, it results in a task not found error.
