### ISSUE TITLE
Access server host inside a task

### ISSUE THREAD

**Issue by guratr** [laravel/envoy#216]
The documentation suggests using something like this for parallel execution
```
@servers(['web-1' => '192.168.1.1', 'web-2' => '192.168.1.2'])

@task('deploy', ['on' => ['web-1', 'web-2'], 'parallel' => true])
    cd site
    ...
    ...
@endtask
```

If all of your sites live on different servers, you always can create "site" symlink on server to your site path.
But when you have multiple sites on the same server, for example 
```
@servers(['web-1' => '192.168.1.1', 'web-2' => '192.168.1.1'])
```
there is no way to specify where to "cd" for each site in the task. 

It would be great if we had access to some variable "$currentHost" inside a task

**Comment by driesvints** [comment]
If you want to propose something feel free to send in a PR 👍

**Comment by Oxicode** [comment]
I like your idea @guratr
Please create PR 🙏

**Comment by guratr** [comment]
> I like your idea @guratr
> Please create PR 🙏

I created PR, but unfortunately it was rejected 😭.
If you need this functionality, you can use my my version [here](https://github.com/guratr/envoy). 
You can check out [pull request](https://github.com/laravel/envoy/pull/217) to see how it works.

**Comment by Oxicode** [comment]
OK, i go to your repo.

**Comment by rluetke** [comment]
I found out, that I can use $__container->getServer($name) to access a server in the TaskContainer https://github.com/laravel/envoy/blob/2.x/src/TaskContainer.php.
Hope this helps!
