### ISSUE TITLE
Can't get value of snake case variables

### ISSUE THREAD

**Issue by ybert** [laravel/envoy#231]
- Envoy Version: 2.7.0
- Laravel Version: 8.61.0
- PHP Version: 7.3

### Description:
It seems that it is not possible to set snake case variables for envoy run deploy

### Steps To Reproduce:
Envoy.blade.php :
```php
@servers(['deployment' => '127.0.0.1'])

@setup
    if (empty($user)) {
        exit('ERROR: $user var empty or not defined');
    }
    if (empty($host)) {
        exit('ERROR: $host var empty or not defined');
    }
    if (empty($app_dir)) {
        exit('ERROR: $app_dir var empty or not defined');
    }
    if (empty($release_path)) {
        exit('ERROR: $release_path var empty or not defined');
    }
@endsetup

@task('deploy', ['on' => 'deployment'])
	exit ("deploy");
@endtask
```

When I run ```vendor/bin/envoy run deploy --user=www --host=staging.company.com --app_dir=/home/www/public```
I get ```ERROR: $app_dir var empty or not defined```

So it seems that it works perfectly with non snake case variables like --user or --host but not with --app_dir

**Comment by driesvints** [comment]
This is indeed not supported.

**Comment by ybert** [comment]
@driesvints It was supported in previous version of Envoy (1.*)
It seems Hyphen case is not supported. So we have to call our variables like --appdir or --releasepath
Its not very readable.

**Comment by driesvints** [comment]
If you can come up with a PR that implements this in a clean way we may consider it.
