### ISSUE TITLE
Deprecated: file_exists()

### ISSUE THREAD

**Issue by zarulizham** [laravel/envoy#237]
- Envoy Version: 2.7.2
- Laravel Version: 8.77.1
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8

### Description:

I got this warning message when executing `envoy run deploy`

`Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in /builds/xxxxxx/yyyy/vendor/laravel/envoy/src/Console/RunCommand.php on line 222`

<img width="699" alt="image" src="https://user-images.githubusercontent.com/10229855/147948645-59d4e268-e684-4ce0-bc8d-6348f20970eb.png">

### Steps To Reproduce:

Run `envoy run deploy`, first line will appear those warning.

**Comment by driesvints** [comment]
This is a deprecation error and not a real issue. We'll update this call over time to make use of something else. For now, please remove deprecation warnings from your PHP runtime.
