### ISSUE TITLE
Completion hooks as commands on remote server

### ISSUE THREAD

**Issue by Tofandel** [laravel/envoy#240]
Right now there is no way to cleanup after a failed task, because the @error hook only executes php locally

It would be nice to be able to run a script on the remote server when the build fails, so that we can cleanup the files that we created

**Comment by driesvints** [comment]
We don't have plans for this ourselves atm but we're open to PR's if you want to try one 👍

**Comment by Tofandel** [comment]
Should I open a PR on 2.x or master for that?
