### ISSUE TITLE
Pass bash variables/arrays to php (and vice versa)

### ISSUE THREAD

**Issue by victorelec14** [laravel/envoy#244]
Hi,

Is there any chance to save bash values in PHP Setup variables? or to be able to execute php code remotely?

For example I am trying to list all the directories on the server so I can run "composer install" on each of those folders.

You could do it by passing the variable by command:
>  ./vendor/bin/envoy run deploy --on=production --branch=master --dir /home/user/dir1
>  ./vendor/bin/envoy run deploy --on=production --branch=master --dir /home/user/dir2
>  ./vendor/bin/envoy run deploy --on=production --branch=master --dir /home/user/dir3

but the problem is that I am going to use it in CI and I cannot get the directories of the server to be able to do each task.

I also tried to create a Variable bash in the @Setup and by ssh try to pass the values but it didn't work.

Do you have any idea how to do it or something similar already exists?

```php
@servers([ 'production' => ['user@domain.com'] ])

@setup
    $folder = '/home/user/'
    $dirsOnServer = [];
@endsetup

@story('deploy')
    get_dirs
    {{-- git --}}
    composer_install
@endstory

@task('get_dirs', ['on' => $on])

    @php
        $dir = new DirectoryIterator($folder);
        foreach ($dir as $fileinfo) {
            if ($fileinfo->isDir() && !$fileinfo->isDot()) {
                $dirsOnServer[] = $fileinfo->getFilename();
            }
        }
    @endphp
@endtask

@task('composer_install', ['on' => $on])
    @foreach($dirsOnServer as $dir)
        cd {{ $dir }}
        composer install 
    @endforeach
@endtask
```

Bash variable with the dirs
```php
@task('get_dirs_bash', ['on' => $on])
    dirsOnServer = ()
    for d in {{$folder}}* ; do
        dirsOnServer+=($d)
    done

    for d in dirsOnServer ; do
        echo "$d"
    done
@endtask
```
Thanks !

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
