### ISSUE TITLE
PHP 8.2 Deprecated

### ISSUE THREAD

**Issue by kovspace** [laravel/envoy#258]
- Envoy Version: 2.8.4
- Laravel Version: 9.43.0
- PHP Version: 8.2.0

### Description:

Deprecated: Creation of dynamic property Laravel\Envoy\Console\RunCommand::$input is deprecated in /vendor/laravel/envoy/src/Console/Command.php on line 21

Deprecated: Creation of dynamic property Laravel\Envoy\Console\RunCommand::$output is deprecated in /vendor/laravel/envoy/src/Console/Command.php on line 22

### Steps To Reproduce:

CLI: envoy run deploy

**Comment by driesvints** [comment]
Thanks, I sent in a PR to rectify this!
