### ISSUE TITLE
support for the HostKeyAlgorithms and PubkeyAcceptedKeyTypes options 

### ISSUE THREAD

**Issue by fh32000** [laravel/envoy#260]
Dear laravel/envoy developers,

We are using the laravel/envoy package to deploy our code to a remote server using GitHub Actions. We have encountered an issue with host key algorithm negotiation when connecting to the server, and we would like to request support for the HostKeyAlgorithms and PubkeyAcceptedKeyTypes options in the laravel/envoy package.

Currently, we are specifying the HostKeyAlgorithms and PubkeyAcceptedKeyTypes options as arguments to the ssh command in the SSH_COMMAND environment variable. However, this requires us to manually set the SSH_COMMAND variable in our GitHub Actions workflow, which can be error-prone.
code
```
      - name: Run Envoy
        run: |
          composer global require laravel/envoy
          ~/.composer/vendor/bin/envoy run deploy --branch=testing
        env:
          SSH_COMMAND: ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
```
error
```
[user@xx.xx.xx.xxx]: Unable to negotiate with xx.xx.xx.xxx port 22: no matching host key type found. Their offer: ssh-rsa,ssh-rsa-cert-v01@openssh.com,ssh-dss
[✗] This task did not complete successfully on one of your servers.
Error: Process completed with exit code 255.
```

We believe that adding support for the HostKeyAlgorithms and PubkeyAcceptedKeyTypes options in the laravel/envoy package would improve the usability and reliability of the package, and make it easier for users to resolve host key algorithm negotiation issues.

Thank you for considering our request.

Sincerely,
fh32000

**Comment by fh32000** [comment]
Here are a few suggestions for adding support for the HostKeyAlgorithms and PubkeyAcceptedKeyTypes options in the laravel/envoy package:

1- Add a configuration option to the laravel/envoy package to allow users to specify the HostKeyAlgorithms and PubkeyAcceptedKeyTypes options. Users could then set these options in the envoy.php configuration file or as environment variables.

2- Add a new ssh directive to the laravel/envoy package that allows users to specify the HostKeyAlgorithms and PubkeyAcceptedKeyTypes options. Users could then specify these options in their Envoy.blade.php script, like this:


```
@ssh(['HostKeyAlgorithms' => '+ssh-rsa', 'PubkeyAcceptedKeyTypes' => '+ssh-rsa'])
@servers(['web' => 'user@xx.xx.xx.xxx'])

@task
deploy_code() {
    cd /home/pidcehzw9w1i
    ...
    
```
3- Add a new option to the @servers directive that allows users to specify the HostKeyAlgorithms and PubkeyAcceptedKeyTypes options. Users could then specify these options in their Envoy.blade.php script, like this:

```
@servers(['web' => 'user@xx.xx.xx.xxx', 'options' => ['HostKeyAlgorithms' => '+ssh-rsa', 'PubkeyAcceptedKeyTypes' => '+ssh-rsa']])

@task
deploy_code() {
    cd /home/pidce
```

**Comment by driesvints** [comment]
If the PR isn't too complicated then I think we could accept something 👍 

Nr. 3 looks best to me.
