### ISSUE TITLE
ERROR: ssh: Could not resolve hostname

### ISSUE THREAD

**Issue by ismaail** [laravel/envoy#271]
### Envoy Version

2.x

### Laravel Version

10.10

### PHP Version

8.2.14

### Database Driver & Version

Postgress 15

### Description

After `composer:update` with the commit e64f6fbf941439cc52c24519a6ee24af68b47ccf

running `envoy run deploy`, I get the 

```
[smith@140.130.150.100-p22]: ssh: Could not resolve hostname 140.130.150.100-p22: Name or service not known
[✗] This task did not complete successfully on one of your servers.
```

### Steps To Reproduce

1. run `composer update`
2. run `envoy run deploy`

---

**Envoy.blade.php** file:

```blade
{{-- Setup --}}
@setup
    $user = 'smith';
    $server = '140.130.150.100';
    $port = 22;
    $dir = '/home/smith/www/project_name';
    $branch = 'develop';
@endsetup

{{-- Servers --}}
@servers(['web' => "{$user}@{$server} -p {$port}"])

{{-- Deploy --}}
@story('deploy', ['on' => 'web', 'confirm' => true])
    git
@endstory

{{-- GIT Task --}}
@task('git')
    cd {{ $dir }}

    echo "Run git pull in $(pwd)"
    git pull origin {{ $branch }}
@endtask
```

**Comment by driesvints** [comment]
@ismaail this hasn't been released yet. How are you pulling in the commit? Can you share your `composer.json`?

Ping @devajmeireles can you have a look and provide a fix?

**Comment by ismaail** [comment]
I'm using a global `composer.json` to use **Envoy** in all my projects,

 I guess it's the `"minimum-stability": "dev",`

```
{
    "require": {
        "phpmd/phpmd": "dev-master",
        "squizlabs/php_codesniffer": "dev-master",
        "laravel/envoy": "^2.0",
        "vimeo/psalm": "^4.3",
        "phpstan/phpstan": "^1.4"
    },
    "minimum-stability": "dev",
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": false
        }
    }
}
```

**Comment by devajmeireles** [comment]
Sure, @driesvints ! I'll take a look at it this afternoon.

**Comment by devajmeireles** [comment]
Done, @driesvints !

Check this: https://github.com/laravel/envoy/pull/272

**Comment by driesvints** [comment]
Closing this one since a PR was opened. Thanks
