### ISSUE TITLE
Feature request: re-use SSH connections?

### ISSUE THREAD

**Issue by ChrisHardie** [laravel/envoy#273]
From what I can tell, envoy opens a new SSH connection to the target server for each task that it runs. (If there is a way to change that behavior, I could not easily find it.)

This created an issue for me because the server I was deploying to had a ufw rate limiting rule in place that prevented more than 6 SSH connections from any given IP address within a 30 second period. A single story with multiple tasks couldn't finish without getting a transient SSH "connection refused" error.

The use of rate limiting on port 22 appears to be a growing best practice suggested in various "setting up a new Ubuntu server" guides that I've found, and that I followed in this case, to prevent DoS attacks.

I can adjust the use of rate limiting on my servers, but it prompted me to wonder if envoy could re-use a single SSH connection in the context of a given run, to reduce resource usage and avoid looking like an attack?

**Comment by driesvints** [comment]
Hi there. I agree that would be useful. Not you could send in a PR for us to look at we can give it a go perhaps 👍
