### ISSUE TITLE
Incorrect task variables behavior

### ISSUE THREAD

**Issue by punyflash** [laravel/envoy#276]
### Envoy Version

2.9.0

### Laravel Version

11.2.0

### PHP Version

8.3.4

### Description

On [task hooks](https://laravel.com/docs/11.x/envoy#completion-hooks) as it documented on official documentation, there is defined `$task` variable. This variable also used on notification directives like `@slack`, `@telegram`, `@discord`, `@microsoftTeams` to report which task was runned by envoy.

However, right now, the `$task` variable is always `null` on those hooks:
```blade.php
@success
    dump(get_defined_vars())
@endsuccess
```

```sh
...
  "task" => null
  "__path" => "/var/www/html/Envoy.blade.php"
  "__compiler" => Laravel\Envoy\Compiler^ {#95}
  "__data" => array:1 [
    "__task" => "test"
  ]
  "__serversOnly" => false
  "__dir" => "/var/www/html"
  "__envoyPath" => "/var/www/html/Envoy3fd1144bc88ba1cca0b706255068ac50.php"
  "__container" => Laravel\Envoy\TaskContainer^ {#58}
  "__task" => "test"
...
```
The correct task name is currently stored in `$__task` variable. In order to make notification report a correct task name, right now you need to set `$task` variable manually:

```blade.php
@success
    $task = $__task;

    @telegram(env('TELEGRAM_BOT_TOKEN'), env('TELEGRAM_USER_ID'))
@endsuccess
```
This doesn't look correct. I believe that either the notification directives should use the `$__task` variable and the correct variable should be specified in the documentation, or the value of the `$task` variable should also be updated correctly.

### Steps To Reproduce

Here is envoy script I used for testing

```blade.php
@include('vendor/autoload.php')

@setup
    Dotenv\Dotenv::create(Illuminate\Support\Env::getRepository(),  __DIR__)->load();
@endsetup

@servers(['local' => '127.0.0.1'])

@task('test')
    echo 'Hello World!'
@endtask

@success
    $task = $__task;

    if (env('TELEGRAM_BOT_TOKEN') && env('TELEGRAM_USER_ID') && $task === 'test') {
        @telegram(env('TELEGRAM_BOT_TOKEN'), env('TELEGRAM_USER_ID'))
    }
@endsuccess

```

**Comment by punyflash** [comment]
I believe this is related to #166 and #254

**Comment by driesvints** [comment]
We'd welcome a PR to make this possible 👍
