### ISSUE TITLE
The Laravel Envoy documentation could mention that `.bashrc` isn't run so common commands like `sail` and `npm install` might not work

### ISSUE THREAD

**Issue by spinalwiz** [laravel/envoy#277]
Some common commands a user might use during deployment such as `sail` and `npm` might not work because .bashrc isn't executed. 

The sail alias is set up in .bashrc as well as nvm (for selecting the version of Node to use)

**Comment by driesvints** [comment]
Thanks but please just PR anything you want to change in the docs.
