### ISSUE TITLE
Add Artisan Command to Simplify Envoy Deployment

### ISSUE THREAD

**Issue by rjsamra** [laravel/envoy#279]
**Description**: 

Currently, deploying with Laravel Envoy requires the command `php vendor/bin/envoy run deploy`. To simplify this process and improve the developer experience, I propose adding an Artisan command that wraps the Envoy deployment task. 

With this feature, users could deploy their projects using a simpler command like `php artisan deploy` or `php artisan en:deploy`.

**Suggested Implementation**:

1. Add a new Artisan command (`deploy` or `en:deploy`) within the Laravel project.
2. The command will internally execute `php vendor/bin/envoy run deploy`.
3. Optionally, allow the new command to accept any parameters or options that would be passed to the Envoy command.

**Benefits**:

- Streamlines the deployment process.
- Reduces command length and complexity.
- Integrates Envoy more seamlessly into the Laravel ecosystem.

**Example Usage**:
```bash
php artisan deploy
# or
php artisan en:deploy
```

This feature would provide a more Laravel-centric deployment workflow, enhancing usability for developers.

---

**Comment by driesvints** [comment]
Thanks. We currently have no plans for this sorry.
